import type { LegendaryEffect } from '../types';

export const legendaryEffects: LegendaryEffect[] = [
    // ⭐ 1 STAR
    {
        id: '1',
        stars: 1,
        name: 'Acechante',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '2',
        stars: 1,
        name: 'Adictivo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '3',
        stars: 1,
        name: 'Antiblindaje',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '4',
        stars: 1,
        name: 'Aristócrata',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '5',
        stars: 1,
        name: 'Asesino',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '6',
        stars: 1,
        name: 'Autoestim',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '7',
        stars: 1,
        name: 'Berserker',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '8',
        stars: 1,
        name: 'Camaleónico',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '9',
        stars: 1,
        name: 'Cazador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '10',
        stars: 1,
        name: 'Cazamutantes',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '11',
        stars: 1,
        name: 'Cazanecrófagos',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '12',
        stars: 1,
        name: 'Cazarrobots',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '13',
        stars: 1,
        name: 'Curativo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '14',
        stars: 1,
        name: 'Cuádruple',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '15',
        stars: 1,
        name: 'Dos tiros',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '16',
        stars: 1,
        name: 'Ensangrentado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '17',
        stars: 1,
        name: 'Exterminador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '18',
        stars: 1,
        name: 'Fanático',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '19',
        stars: 1,
        name: 'Francotirador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '20',
        stars: 1,
        name: 'Furioso',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '21',
        stars: 1,
        name: 'Infiltración',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '22',
        stars: 1,
        name: 'Inflexible',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '23',
        stars: 1,
        name: 'Insaciable',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '24',
        stars: 1,
        name: 'Lucidez',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '25',
        stars: 1,
        name: 'Mastodonte',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '26',
        stars: 1,
        name: 'Mutante',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '27',
        stars: 1,
        name: 'Nocturno',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '28',
        stars: 1,
        name: 'Peso pesado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '29',
        stars: 1,
        name: 'Provocador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '30',
        stars: 1,
        name: 'Reconstituyente',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '31',
        stars: 1,
        name: 'Regeneración',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '32',
        stars: 1,
        name: 'Salvaje',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '33',
        stars: 1,
        name: 'Salvavidas',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '34',
        stars: 1,
        name: 'Sibarita',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '35',
        stars: 1,
        name: 'Silenciador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '36',
        stars: 1,
        name: 'Suprarrenal',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '37',
        stars: 1,
        name: 'Vampiro',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '38',
        stars: 1,
        name: 'Vanguardia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '39',
        stars: 1,
        name: 'Verdugo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '40',
        stars: 1,
        name: 'Ágil',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },

    // ⭐⭐ 2 STARS
    {
        id: '41',
        stars: 2,
        name: 'Acelerón',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '42',
        stars: 2,
        name: 'Agilidad',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '43',
        stars: 2,
        name: 'Analgésico',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '44',
        stars: 2,
        name: 'Antiséptico',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '45',
        stars: 2,
        name: 'Asesino a sueldo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '46',
        stars: 2,
        name: 'Carisma',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '47',
        stars: 2,
        name: 'Carterista',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '48',
        stars: 2,
        name: 'Elementalista',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '49',
        stars: 2,
        name: 'Envenenador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '50',
        stars: 2,
        name: 'Estable',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '51',
        stars: 2,
        name: 'Explosivo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '52',
        stars: 2,
        name: 'Feroz',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '53',
        stars: 2,
        name: 'Fuerza',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '54',
        stars: 2,
        name: 'Glotonería',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '55',
        stars: 2,
        name: 'Golpeador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '56',
        stars: 2,
        name: 'Ignífugo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '57',
        stars: 2,
        name: 'Incapacitante',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '58',
        stars: 2,
        name: 'Inercia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '59',
        stars: 2,
        name: 'Inteligencia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '60',
        stars: 2,
        name: 'Materiales peligrosos',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '61',
        stars: 2,
        name: 'Percepción',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '62',
        stars: 2,
        name: 'Potenciado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '63',
        stars: 2,
        name: 'Resistencia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '64',
        stars: 2,
        name: 'Respuesta',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '65',
        stars: 2,
        name: 'Robusto',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '66',
        stars: 2,
        name: 'Suerte',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '67',
        stars: 2,
        name: 'Tibio',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '68',
        stars: 2,
        name: 'VATS mejorado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '69',
        stars: 2,
        name: 'Vital',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '70',
        stars: 2,
        name: 'Veloz',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '71',
        stars: 2,
        name: 'Último disparo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '72',
        stars: 2,
        name: 'Resistencia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '73',
        stars: 2,
        name: 'Resistente',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '74',
        stars: 2,
        name: 'Resplandeciente',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '75',
        stars: 2,
        name: 'Saludable',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '76',
        stars: 2,
        name: 'Suerte',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '77',
        stars: 2,
        name: 'Tóxico',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '78',
        stars: 2,
        name: 'VATS optimizado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },

    // ⭐⭐⭐ 3 STARS
    {
        id: '79',
        stars: 3,
        name: 'Acrobático',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '80',
        stars: 3,
        name: 'Agente secreto',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '81',
        stars: 3,
        name: 'Agilidad',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '82',
        stars: 3,
        name: 'Alpinista',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '83',
        stars: 3,
        name: 'Bloqueador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '84',
        stars: 3,
        name: 'Brío',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '85',
        stars: 3,
        name: 'Buzo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '86',
        stars: 3,
        name: 'Bárbaro',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '87',
        stars: 3,
        name: 'Caballero',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '88',
        stars: 3,
        name: 'Carisma',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '89',
        stars: 3,
        name: 'Centinela',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '90',
        stars: 3,
        name: 'Defensor',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '91',
        stars: 3,
        name: 'Descerrajador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '92',
        stars: 3,
        name: 'Disipación',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '93',
        stars: 3,
        name: 'Durabilidad',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '94',
        stars: 3,
        name: 'Electrificado',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '95',
        stars: 3,
        name: 'En llamas',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '96',
        stars: 3,
        name: 'Fantasmal',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '97',
        stars: 3,
        name: 'Firme',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '98',
        stars: 3,
        name: 'Fuerza',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '99',
        stars: 3,
        name: 'Golpe de suerte',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '100',
        stars: 3,
        name: 'Gélido',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '101',
        stars: 3,
        name: 'Infatigable',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '102',
        stars: 3,
        name: 'Inteligencia',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '103',
        stars: 3,
        name: 'Ligeros',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '104',
        stars: 3,
        name: 'Municionero',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '105',
        stars: 3,
        name: 'Percepción',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '106',
        stars: 3,
        name: 'Peso ligero',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '107',
        stars: 3,
        name: 'Portador de armas',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '108',
        stars: 3,
        name: 'Rata de carga',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '109',
        stars: 3,
        name: 'Reflejo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },

    // ⭐⭐⭐⭐ 4 STARS
    {
        id: '110',
        stars: 4,
        name: 'Agresor',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '111',
        stars: 4,
        name: 'Amante de la adrenalina',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '112',
        stars: 4,
        name: 'Bravucón',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '113',
        stars: 4,
        name: 'Carga',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '114',
        stars: 4,
        name: 'Cargador al máximo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '115',
        stars: 4,
        name: 'Chu, chu',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '116',
        stars: 4,
        name: 'Conductor',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '117',
        stars: 4,
        name: 'Corredor',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '118',
        stars: 4,
        name: 'Electricista',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '119',
        stars: 4,
        name: 'Escáner',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '120',
        stars: 4,
        name: 'Estabilizador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '121',
        stars: 4,
        name: 'Frío glacial',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '122',
        stars: 4,
        name: 'Incondicional',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '123',
        stars: 4,
        name: 'Inspiración radiactiva',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '124',
        stars: 4,
        name: 'Liberador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '125',
        stars: 4,
        name: 'Localizador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '126',
        stars: 4,
        name: 'Machacador',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '127',
        stars: 4,
        name: 'Matasanos',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '128',
        stars: 4,
        name: 'Matón',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '129',
        stars: 4,
        name: 'Miasma',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '130',
        stars: 4,
        name: 'Pirómano',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '131',
        stars: 4,
        name: 'Propulsión',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '132',
        stars: 4,
        name: 'Pulido',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '133',
        stars: 4,
        name: 'Pétreo',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '134',
        stars: 4,
        name: 'Ranger',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '135',
        stars: 4,
        name: 'Reflectante',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '136',
        stars: 4,
        name: 'Rejuvenecedor',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '137',
        stars: 4,
        name: 'Rompecombos',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '138',
        stars: 4,
        name: 'Rompehuesos',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '139',
        stars: 4,
        name: 'Rompelímites',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '140',
        stars: 4,
        name: 'Víbora',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
    {
        id: '141',
        stars: 4,
        name: 'Égida',
        description: '',
        category: '',
        ghoul: false,
        unlocked: true,
    },
];
