import type { LegendaryEffect } from '../types';

export const legendaryEffects: LegendaryEffect[] = [
    // ⭐ 1 STAR
    {
        id: '1',
        stars: 1,
        name: 'Acechante',
        description: '+100% daño de ataque sigiloso',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '2',
        stars: 1,
        name: 'Adictivo',
        description: 'El daño aumenta hasta un 100% por adicciones',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '3',
        stars: 1,
        name: 'Antiblindaje',
        description: '+50% de penetración de armadura',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '4',
        stars: 1,
        name: 'Aristócrata',
        description:
            '(Armas) Hasta +50% de daño en función de las tapas que tengas. (Armaduras) Refleja el daño en función del número de tapas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '5',
        stars: 1,
        name: 'Asesino',
        description:
            '(Armas) +50% daño a humanos. (Armaduras) -15% de daño procedente de humanos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '6',
        stars: 1,
        name: 'Autoestim',
        description:
            'Utiliza automáticamente un estimulante si te dan y tienes 25% o menos de salud. Funciona una vez cada 60 segundos',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '7',
        stars: 1,
        name: 'Berserker',
        description:
            'El daño aumenta hasta un 50% a medida que disminuye el efecto Resistencia al daño',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '8',
        stars: 1,
        name: 'Camaleónico',
        description:
            'Te vuelves invisible mientras te mueves con sigilo o permaneces inmóvil',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '9',
        stars: 1,
        name: 'Cazador',
        description:
            '(Armas) +50% de daño a los animales. (Armaduras) -15% de daño de los animales',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '10',
        stars: 1,
        name: 'Cazamutantes',
        description:
            '(Armas) +50% de daño a los supermutantes. (Armaduras) -15% de daño de los supermutantes',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '11',
        stars: 1,
        name: 'Cazanecrófagos',
        description:
            '(Armas) +50% de daño a los necrófagos. (Armaduras) -15% de daño de los necrófagos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '12',
        stars: 1,
        name: 'Cazarrobots',
        description:
            '(Armas) +50% de daño a los robots. (Armaduras) -15% de daño de los robots',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '13',
        stars: 1,
        name: 'Curativo',
        description:
            'Los ataques curarán a los objetivos aliados un 5% de salud',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '14',
        stars: 1,
        name: 'Cuádruple',
        description: '+300% capacidad de munición',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '15',
        stars: 1,
        name: 'Dos tiros',
        description: '+1 proyectiles. +75% de daño',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '16',
        stars: 1,
        name: 'Ensangrentado',
        description:
            'El daño aumenta hasta un 130% a medida que la salud disminuye',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '17',
        stars: 1,
        name: 'Exterminador',
        description:
            '(Armas) +50% de daño a los mirelurks e insectos. (Armaduras) -15% de daño de los mirelurks e insectos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '18',
        stars: 1,
        name: 'Fanático',
        description:
            '(Armas) +50% de daño a los calcinados. (Armaduras) -15% de daño de los calcinados',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '19',
        stars: 1,
        name: 'Francotirador',
        description: '+100% de daño a objetivos lejanos',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '20',
        stars: 1,
        name: 'Furioso',
        description:
            '+5% de daño por acumulación de embestidas y +9 de acumulaciones máximas',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '21',
        stars: 1,
        name: 'Infiltración',
        description:
            'Una vez cada 30 segundos, recibir un golpe cuerpo a cuerpo produce invisibilidad',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '22',
        stars: 1,
        name: 'Inflexible',
        description:
            'Obtén un máximo de +3 a todas las estadísticas SPECIAL (salvo RES) cuando tengas poca salud',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '23',
        stars: 1,
        name: 'Insaciable',
        description:
            'La salud máxima aumenta hasta +40 a medida que se llenan los medidores de hambre y sed',
        category: ['armor', 'power armor'],
        race: ['human'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '24',
        stars: 1,
        name: 'Lucidez',
        description:
            '(Armas) El daño aumenta hasta un 40% a medida que se llena el medidor de salvajismo. (Armaduras) La reducción del daño aumenta hasta un 6% a medida que se llena el medidor de salvajismo',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '25',
        stars: 1,
        name: 'Mastodonte',
        description:
            'El daño aumenta hasta un 100% a medida que la salud aumenta',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '26',
        stars: 1,
        name: 'Mutante',
        description:
            '(Armas) El daño aumenta hasta 50% a medida que sufres mutaciones. (Armaduras) Hasta un 5% de reducción de daño a medida que sufres mutaciones',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '27',
        stars: 1,
        name: 'Nocturno',
        description:
            '(Armas) +50% de daño al permanecer oculto. (Armaduras) +4 de PER y agilidad al permanecer oculto',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '28',
        stars: 1,
        name: 'Peso pesado',
        description: 'Hasta un 10% de reducción de daño cuanto mas peso lleves',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '29',
        stars: 1,
        name: 'Provocador',
        description:
            '+50% de daño contra objetivos con la salud por encima del 60%',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '30',
        stars: 1,
        name: 'Reconstituyente',
        description:
            'Hasta un 10% de reducción de daño cuanto menos porcentaje de salud tengas',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '31',
        stars: 1,
        name: 'Regeneración',
        description: '+0.5% velocidad de curación',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '32',
        stars: 1,
        name: 'Salvaje',
        description: 'Las bajas aceleran la transformación en salvaje',
        category: ['melee'],
        race: ['ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '33',
        stars: 1,
        name: 'Salvavidas',
        description:
            'Te reanimas automáticamente con un estimulante. El tiempo de recarga es de 5 minutos, pero cada módulo salvavidas adicional lo reduce en 60 segundos',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '34',
        stars: 1,
        name: 'Sibarita',
        description:
            'El daño aumenta hasta un 40% a medida que se llenan los medidores de hambre y sed',
        category: ['ranged', 'melee'],
        race: ['human'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '35',
        stars: 1,
        name: 'Silenciador',
        description:
            'El daño que inflinje el objetivo al que atacas se reduce un 25% durante 5 segundos',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '36',
        stars: 1,
        name: 'Suprarrenal',
        description:
            '(Armas) +10% de daño por baja en una racha de bajas. (Armaduras) +10 de resistencia al daño y a la energía por baja en una racha de bajas (máximo 10)',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '37',
        stars: 1,
        name: 'Vampiro',
        description:
            'Regenera un 2% de salud durante 2 segundos al golpear a un objetivo',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '38',
        stars: 1,
        name: 'Vanguardia',
        description:
            'Hasta un 6% de reducción de daño a medida que aumenta la salud (el % máximo depende de tus puntos máximos de salud)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '39',
        stars: 1,
        name: 'Verdugo',
        description:
            '+50% de daño cuando el enemigo tiene menos del 40% de la salud',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },

    // ⭐⭐ 2 STARS
    {
        id: '41',
        stars: 2,
        name: 'Acelerón',
        description:
            'Consigue puntos de acción durante una racha de bajas. El efecto se vuelve mas potente cuanto mas larga sea la racha',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '42',
        stars: 2,
        name: 'Agilidad',
        description: '+2 Agilidad',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '43',
        stars: 2,
        name: 'Analgésico',
        description:
            'Consigue salud a los largo del tiempo durante las rachas de bajas. El efecto se vuelve mas potente cuanto mas larga sea la racha',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '44',
        stars: 2,
        name: 'Antiséptico',
        description: '+25% resistencia a enfermedades medioambientales',
        category: ['armor', 'power armor'],
        race: ['human'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '45',
        stars: 2,
        name: 'Asesino a sueldo',
        description: '+25% de daño al puntar',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '46',
        stars: 2,
        name: 'Carisma',
        description: '+2 Carisma',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '47',
        stars: 2,
        name: 'Carterista',
        description:
            'Las bajas tienen un 50% de probabilidad de otorgar una pequeña cantidad de tapas',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '48',
        stars: 2,
        name: 'Elementalista',
        description: 'Aumenta en +25 todas las resistencias',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '49',
        stars: 2,
        name: 'Envenenador',
        description: '+50 resistencia al veneno',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '50',
        stars: 2,
        name: 'Estable',
        description: '+25% de daño cuerpo a cuerpo al mantenerte inmóvil',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '51',
        stars: 2,
        name: 'Explosivo',
        description:
            'Los proyectiles explotan e inflingen un daño de arma del 20%',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '52',
        stars: 2,
        name: 'Feroz',
        description:
            'Refuerza el aguante de las extremidades según la racha de bajas',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '53',
        stars: 2,
        name: 'Fuerza',
        description: '+2 Fuerza',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '54',
        stars: 2,
        name: 'Glotonería',
        description: 'El hambre y la sed aumentan un 10% mas despacio',
        category: ['armor', 'power armor'],
        race: ['human'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '55',
        stars: 2,
        name: 'Golpeador',
        description: '+50% daño por golpe',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '56',
        stars: 2,
        name: 'Ignífugo',
        description: '+50 resistencia al fuego',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '57',
        stars: 2,
        name: 'Incapacitante',
        description: '+50% daño a las extremidades',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '58',
        stars: 2,
        name: 'Inercia',
        description: 'Recuperas 15 puntos de acción con cada baja',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '59',
        stars: 2,
        name: 'Inteligencia',
        description: '+2 Inteligencia',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '60',
        stars: 2,
        name: 'Materiales peligrosos',
        description: '+50 resistencia a la radiación',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '61',
        stars: 2,
        name: 'Percepción',
        description: '+2 Percepción',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '62',
        stars: 2,
        name: 'Peso pesado',
        description: '+40% daño de ataque potente',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '142',
        stars: 2,
        name: 'Potenciado',
        description: '+5% regeneración de puntos de acción',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '63',
        stars: 2,
        name: 'Resistencia',
        description: '+2 Resistencia',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '64',
        stars: 2,
        name: 'Respuesta',
        description: '+50% reflejo del daño bloqueado',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '65',
        stars: 2,
        name: 'Robusto',
        description: 'Recibe un 7% menos de daño por explosión',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '66',
        stars: 2,
        name: 'Suerte',
        description: '+2 Suerte',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '67',
        stars: 2,
        name: 'Tibio',
        description: '+50 resistencia criogénica',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '68',
        stars: 2,
        name: 'VATS mejorado',
        description: '+50% probabilidad de golpear un objetivo en VATS',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '70',
        stars: 2,
        name: 'Veloz',
        description: '+25% velocidad del arma',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '69',
        stars: 2,
        name: 'Vital',
        description: '+50% daño crítico',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '71',
        stars: 2,
        name: 'Último disparo',
        description:
            'La última bala de un cargador tiene una probabilidad del 25% de infringir un +100% de daño',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    // ⭐⭐⭐ 3 STARS
    {
        id: '79',
        stars: 3,
        name: 'Acrobático',
        description: '-50% de daño por caída',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '80',
        stars: 3,
        name: 'Agente secreto',
        description:
            'Haces 25% menos ruido al moverte con sigilo. Se reduce la probabilidad de detección un 25%',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '81',
        stars: 3,
        name: 'Agilidad',
        description: '+3 Agilidad',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '82',
        stars: 3,
        name: 'Alpinista',
        description:
            'El peso de la comida, la bebida y las drogas se reducen un 20%',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '83',
        stars: 3,
        name: 'Bloqueador',
        description: '+15% daño bloqueado',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '84',
        stars: 3,
        name: 'Brío',
        description: 'Aumentan +20 los puntos de acción máximos',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '85',
        stars: 3,
        name: 'Buzo',
        description: 'Respirar bajo el agua',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '86',
        stars: 3,
        name: 'Bárbaro',
        description: '+ Fue por baja en una racha de bajas (10 como máximo)',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '87',
        stars: 3,
        name: 'Caballero',
        description: '10% de reducción de daño al correr',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '88',
        stars: 3,
        name: 'Carisma',
        description: '+3 Carisma',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '89',
        stars: 3,
        name: 'Centinela',
        description: '5% de reducción de daño al permanecer inmóvil',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '90',
        stars: 3,
        name: 'Defensor',
        description:
            '(Armas cuerpo a cuerpo) +40% probabilidad de bloquear automaticamente los ataques. (Armadura) +5% probabilidad de bloquear automaticamente los ataques',
        category: ['melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '91',
        stars: 3,
        name: 'Descerrajador',
        description:
            '+1 habilidad de hackeo. +1 habilidad de forzar cerraduras',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '92',
        stars: 3,
        name: 'Disipación',
        description: '+0.25 recuperación del daño de radiación',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '93',
        stars: 3,
        name: 'Durabilidad',
        description:
            '(Armas) Las armas tardan un 50% mas en romperse. (Armaduras) Las armaduras tardan un 50% mas en romperse',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '94',
        stars: 3,
        name: 'Electrificado',
        description:
            '5% de probabilidad de inflingir 18 de daño de energía por segundo durante 3 segundos a los atacantes cuerpo a cuerpo',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '95',
        stars: 3,
        name: 'En llamas',
        description:
            '5% de probabilidad de inflingir 19 de daño por fuego por segundo durante 3 segundos a los atacantes cuerpo a cuerpo',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '96',
        stars: 3,
        name: 'Fantasmal',
        description:
            '10% de probabilidad de producir invisibilidad en el jugador durante 2 segundos al golpear a un objetivo',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '97',
        stars: 3,
        name: 'Firme',
        description: '+15% resistencia al daño a las extremidades',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '98',
        stars: 3,
        name: 'Fuerza',
        description: '+3 Fuerza',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '99',
        stars: 3,
        name: 'Golpe de suerte',
        description: '+15% carga crítica de VATS adicional',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '100',
        stars: 3,
        name: 'Gélido',
        description:
            '5% de probabilidad de inflingir 12 de daño por hielo por segundo durante 4 segundos a los atacantes cuerpo a cuerpo',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '101',
        stars: 3,
        name: 'Infatigable',
        description: '+50 de resistencia al daño al apuntar',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '102',
        stars: 3,
        name: 'Inteligencia',
        description: '+3 Inteligencia',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '103',
        stars: 3,
        name: 'Ligeros',
        description: '+15% velocidad de recarga',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '104',
        stars: 3,
        name: 'Municionero',
        description: 'El peso de la munición se reduce un 20%',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '143',
        stars: 3,
        name: 'Médico',
        description: '+5% de eficacia de estimulantes, rad-away y rad-x',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '105',
        stars: 3,
        name: 'Percepción',
        description: '+3 Percepción',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '106',
        stars: 3,
        name: 'Peso ligero',
        description: '-90% de peso',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '107',
        stars: 3,
        name: 'Portador de armas',
        description: 'El peso de las armas se reduce un 20%',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '108',
        stars: 3,
        name: 'Rata de carga',
        description: 'El peso de los objetos de chatarra se reduce un 20%',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '109',
        stars: 3,
        name: 'Reflejo',
        description: '+2% probabilidad de esquivar',
        category: ['armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '144',
        stars: 3,
        name: 'Resistencia',
        description: '+3 Resistencia',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '145',
        stars: 3,
        name: 'Resistente',
        description: '+500 a todas las resistencias al recargar',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '146',
        stars: 3,
        name: 'Resplandeciente',
        description: 'Las bajas suman una pequeña cantidad de resplandor',
        category: ['ranged', 'melee'],
        race: ['ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '147',
        stars: 3,
        name: 'Saludable',
        description: 'Aumenta los PS max en 20',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '148',
        stars: 3,
        name: 'Suerte',
        description: '+3 Suerte',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '149',
        stars: 3,
        name: 'Tóxico',
        description:
            '5% de probabilidad de inflingir 12 de daño por veneno por segundo durante 7 segundos a los atacantes cuerpo a cuerpo',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '150',
        stars: 3,
        name: 'VATS optimizado',
        description: '-35% de costo de PA',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '151',
        stars: 3,
        name: 'Ágil',
        description: '+100% de aumento de velocidad al apuntar',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    // ⭐⭐⭐⭐ 4 STARS
    {
        id: '110',
        stars: 4,
        name: 'Agresor',
        description:
            '+12,5 de daño cuerpo a cuerpo y un +12,5% adicional para cada compañero de equipo cercano (hasta un +50% cuando esté todo el equipo)',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '111',
        stars: 4,
        name: 'Amante de la adrenalina',
        description:
            'Aumento de la velocidad de recarga y el ataque cuerpo a cuerpo según la racha de bajas',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '112',
        stars: 4,
        name: 'Bravucón',
        description:
            '+25% de daño por cada extremidad incapacitada del objetivo',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '113',
        stars: 4,
        name: 'Carga',
        description:
            'Los ataques ligeros aumentan la carga que se libera con un ataque pesado (3 cargas como máximo)',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '114',
        stars: 4,
        name: 'Cargador al máximo',
        description:
            '15% de probabilidad de recargar al instante traas golpear a un enemigo (hasta un 75% de probabilidad con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '115',
        stars: 4,
        name: 'Chu, chu',
        description:
            '+1 de rango de Tren del dolor. Los enemigos golpeados con tren del dolor sufren hemorragia y 20 de daño durante 5 segundos',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '116',
        stars: 4,
        name: 'Conductor',
        description:
            'Los impactos críticos restauran 10 de salud y puntops de acción al instante, y 100 mas durante 5 segundos al jugador y al equipo en un radio de 100 metros',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '117',
        stars: 4,
        name: 'Corredor',
        description:
            'Reduce el costo de los puntos de acción un 20% al correr (hasta un -100% con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '118',
        stars: 4,
        name: 'Electricista',
        description:
            'Al recargar emite una onda expansiva que aturde a los enemigos cercanos durante 3 segundos',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '119',
        stars: 4,
        name: 'Escáner',
        description:
            'Reduce el costo de puntos de acción un 5% al atacar con VATS (hasta un -25% con todas las partes)',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '120',
        stars: 4,
        name: 'Estabilizador',
        description:
            'Mejora el cono de fuego, el retroceso y la estabilidad de las armas un 40%',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '121',
        stars: 4,
        name: 'Frío glacial',
        description: '+20 de daño por hielo',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '122',
        stars: 4,
        name: 'Incondicional',
        description:
            'La servoarmadura del usuario y todos los compañeros de equipo en un radio de 50 metros se rompe un 5% mas lento (hasta un 25% mas lento con todas las partes)',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '123',
        stars: 4,
        name: 'Inspiración radiactiva',
        description:
            '+2 de regeneración de puntos de acción a cambio de radiación (hasta +10 de puntos de acción con todas las partes)',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '124',
        stars: 4,
        name: 'Liberador',
        description:
            '+10% de daño por cada enemigo a tu alrededor, hasta un máximo de +50%',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '125',
        stars: 4,
        name: 'Localizador',
        description: '+20% de daño a los puntos débiles',
        category: ['ranged'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '126',
        stars: 4,
        name: 'Machacador',
        description:
            '+10% de daño por acumulación de embestidas y +10 de acumulaciones máximas',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '127',
        stars: 4,
        name: 'Matasanos',
        description:
            'La salud se regenera lentamente (1 de salud por segundo, hasta +5 de salud por segundo con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '128',
        stars: 4,
        name: 'Matón',
        description:
            'Las armas cuerpo a cuerpo inflingen un 5% de daño adicional (hasta un +25% con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '129',
        stars: 4,
        name: 'Miasma',
        description: '+10 de daño por veneno por segundo a objetivos cercanos',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '130',
        stars: 4,
        name: 'Pirómano',
        description:
            'Inflinge un 50% de daño adicional cuando el enemigo está en llamas',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '131',
        stars: 4,
        name: 'Propulsión',
        description:
            'La velocidad y la carrera aumentan un 5% (hasta un +25% con todas las partes)',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '132',
        stars: 4,
        name: 'Pulido',
        description:
            'El arma infringirá mas daño (hasta un +60%) cuanto mejor sea el estado del objeto equipado (+100%)',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '133',
        stars: 4,
        name: 'Pétreo',
        description:
            '+200 de resistencia al daño durante 10 segundos al peermancer quieto (20 segundos de tiempo de recarga. Hasta +1000 con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '134',
        stars: 4,
        name: 'Ranger',
        description:
            'Las armas a distancia inflingen un 5%  de daño adicionas (hasta un +25% con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '135',
        stars: 4,
        name: 'Reflectante',
        description:
            'Devuelve un 10% del daño recibido hacia el atacante. (hasta un 50% con todas las partes)',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: true,
        unlocked: false,
    },
    {
        id: '136',
        stars: 4,
        name: 'Rejuvenecedor',
        description:
            'Obtienes salud y regeneración de puntos de acción a medida que se llenan los medidores de hambre y sed',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '137',
        stars: 4,
        name: 'Rompecombos',
        description:
            '50% de probabilidad de no usar puntos de acción (10% de probabilidad en herramientas eléctricas) al inflingir daño',
        category: ['melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '138',
        stars: 4,
        name: 'Rompehuesos',
        description:
            'Las extremidades incapacitadas explotan e inflingen hasta un 50 de daño por explosión a los enemigos cercanos',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '139',
        stars: 4,
        name: 'Rompelímites',
        description:
            'Cada pieza de la armadura reduce los costos del impacto crítico un 10%. (hasta un -50% con todas las partes)',
        category: ['armor', 'power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '140',
        stars: 4,
        name: 'Víbora',
        description:
            'Inflinge un 50% de daño adicional cuando el enemigo es envenenado',
        category: ['ranged', 'melee'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
    {
        id: '141',
        stars: 4,
        name: 'Égida',
        description:
            'Refuerza en +50 la resistencia al daño físico y a ala energía y en +20 la resistencia al veneno, hielo y fuego al portador y los compañeros de equipo en un radio de 50 metros',
        category: ['power armor'],
        race: ['human', 'ghoul'],
        bounty: false,
        unlocked: false,
    },
];
