import type { LegendaryEffect } from '../types';

export const legendaryEffects: LegendaryEffect[] = [
    // ⭐ 1 STAR
    {
        id: '1',
        stars: 1,
        name: 'Acechante',
        description: '+100% daño de ataque sigiloso',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '2',
        stars: 1,
        name: 'Adictivo',
        description: 'El daño aumenta hasta un 100% por adicciones',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '3',
        stars: 1,
        name: 'Antiblindaje',
        description: '+50% de penetración de armadura',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '4',
        stars: 1,
        name: 'Aristócrata',
        description: '(Armas) Hasta +50% de daño en función de las tapas que tengas. (Armaduras) Refleja el daño en función del número de tapas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '5',
        stars: 1,
        name: 'Asesino',
        description: '(Armas) +50% daño a humanos. (Armaduras) -15% de daño procedente de humanos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '6',
        stars: 1,
        name: 'Autoestim',
        description: 'Utiliza automáticamente un estimulante si te dan y tienes 25% o menos de salud. Funciona una vez cada 60 segundos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '7',
        stars: 1,
        name: 'Berserker',
        description: 'El daño aumenta hasta un 50% a medida que disminuye el efecto Resistencia al daño',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '8',
        stars: 1,
        name: 'Camaleónico',
        description: 'Te vuelves invisible mientras te mueves con sigilo o permaneces inmóvil',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '9',
        stars: 1,
        name: 'Cazador',
        description: '(Armas) +50% de daño a los animales. (Armaduras) -15% de daño de los animales',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '10',
        stars: 1,
        name: 'Cazamutantes',
        description: '(Armas) +50% de daño a los supermutantes. (Armaduras) -15% de daño de los supermutantes',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '11',
        stars: 1,
        name: 'Cazanecrófagos',
        description: '(Armas) +50% de daño a los necrófagos. (Armaduras) -15% de daño de los necrófagos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '12',
        stars: 1,
        name: 'Cazarrobots',
        description: '(Armas) +50% de daño a los robots. (Armaduras) -15% de daño de los robots',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '13',
        stars: 1,
        name: 'Curativo',
        description: 'Los ataques curarán a los objetivos aliados un 5% de salud',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '14',
        stars: 1,
        name: 'Cuádruple',
        description: '+300% capacidad de munición',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '15',
        stars: 1,
        name: 'Dos tiros',
        description: '+1 proyectiles. +75% de daño',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '16',
        stars: 1,
        name: 'Ensangrentado',
        description: 'El daño aumenta hasta un 130% a medida que la salud disminuye',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '17',
        stars: 1,
        name: 'Exterminador',
        description: '(Armas) +50% de daño a los mirelurks e insectos. (Armaduras) -15% de daño de los mirelurks e insectos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '18',
        stars: 1,
        name: 'Fanático',
        description: '(Armas) +50% de daño a los calcinados. (Armaduras) -15% de daño de los calcinados',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '19',
        stars: 1,
        name: 'Francotirador',
        description: '+100% de daño a objetivos lejanos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '20',
        stars: 1,
        name: 'Furioso',
        description: '+5% de daño por acumulación de embestidas y +9 de acumulaciones máximas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '21',
        stars: 1,
        name: 'Infiltración',
        description: 'Una vez cada 30 segundos, recibir un golpe cuerpo a cuerpo produce invisibilidad',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '22',
        stars: 1,
        name: 'Inflexible',
        description: 'Obtén un máximo de +3 a todas las estadísticas SPECIAL (salvo RES) cuando tengas poca salud',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '23',
        stars: 1,
        name: 'Insaciable',
        description: 'La salud máxima aumenta hasta +40 a medida que se llenan los medidores de hambre y sed',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '24',
        stars: 1,
        name: 'Lucidez',
        description: '(Armas) El daño aumenta hasta un 40% a medida que se llena el medidor de salvajismo. (Armaduras) La reducción del daño aumenta hasta un 6% a medida que se llena el medidor de salvajismo',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '25',
        stars: 1,
        name: 'Mastodonte',
        description: 'El daño aumenta hasta un 100% a medida que la salud aumenta',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '26',
        stars: 1,
        name: 'Mutante',
        description: '(Armas) El daño aumenta hasta 50% a medida que sufres mutaciones. (Armaduras) Hasta un 5% de reducción de daño a medida que sufres mutaciones',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '27',
        stars: 1,
        name: 'Nocturno',
        description: '(Armas) +50% de daño al permanecer oculto. (Armaduras) +4 de PER y agilidad al permanecer oculto',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '28',
        stars: 1,
        name: 'Peso pesado',
        description: 'Hasta un 10% de reducción de daño cuanto mas peso lleves',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '29',
        stars: 1,
        name: 'Provocador',
        description: '+50% de daño contra objetivos con la salud por encima del 60%',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '30',
        stars: 1,
        name: 'Reconstituyente',
        description: 'Hasta un 10% de reducción de daño cuanto menos porcentaje de salud tengas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '31',
        stars: 1,
        name: 'Regeneración',
        description: '+0.5% velocidad de curación',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '32',
        stars: 1,
        name: 'Salvaje',
        description: 'Las bajas aceleran la transformación en salvaje',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['ghoul'],
        unlocked: false,
    },
    {
        id: '33',
        stars: 1,
        name: 'Salvavidas',
        description: 'Te reanimas automáticamente con un estimulante. El tiempo de recarga es de 5 minutos, pero cada módulo salvavidas adicional lo reduce en 60 segundos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '34',
        stars: 1,
        name: 'Sibarita',
        description: 'El daño aumenta hasta un 40% a medida que se llenan los medidores de hambre y sed',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human'],
        unlocked: false,
    },
    {
        id: '35',
        stars: 1,
        name: 'Silenciador',
        description: 'El daño que inflinje el objetivo al que atacas se reduce un 25% durante 5 segundos',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '36',
        stars: 1,
        name: 'Suprarrenal',
        description: '(Armas) +10% de daño por baja en una racha de bajas. (Armaduras) +10 de resistencia al daño y a la energía por baja en una racha de bajas (máximo 10)',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '37',
        stars: 1,
        name: 'Vampiro',
        description: 'Regenera un 2% de salud durante 2 segundos al golpear a un objetivo',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '38',
        stars: 1,
        name: 'Vanguardia',
        description: 'Hasta un 6% de reducción de daño a medida que aumenta la salud (el % máximo depende de tus puntos máximos de salud)',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '39',
        stars: 1,
        name: 'Verdugo',
        description: '+50% de daño cuando el enemigo tiene menos del 40% de la salud',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },

    // ⭐⭐ 2 STARS
    {
        id: '41',
        stars: 2,
        name: 'Acelerón',
        description: 'Consigue puntos de acción durante una racha de bajas. El efecto se vuelve mas potente cuanto mas larga sea la racha',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '42',
        stars: 2,
        name: 'Agilidad',
        description: '+2 Agilidad',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '43',
        stars: 2,
        name: 'Analgésico',
        description: 'Consigue salud a los largo del tiempo durante las rachas de bajas. El efecto se vuelve mas potente cuanto mas larga sea la racha',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '44',
        stars: 2,
        name: 'Antiséptico',
        description: '+25% resistencia a enfermedades medioambientales',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '45',
        stars: 2,
        name: 'Asesino a sueldo',
        description: '+25% de daño al puntar',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '46',
        stars: 2,
        name: 'Carisma',
        description: '+2 Carisma',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '47',
        stars: 2,
        name: 'Carterista',
        description: 'Las bajas tienen un 50% de probabilidad de otorgar una pequeña cantidad de tapas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '48',
        stars: 2,
        name: 'Elementalista',
        description: 'Aumenta en +25 todas las resistencias',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '49',
        stars: 2,
        name: 'Envenenador',
        description: '+50 resistencia al veneno',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '50',
        stars: 2,
        name: 'Estable',
        description: '+25% de daño cuerpo a cuerpo al mantenerte inmóvil',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '51',
        stars: 2,
        name: 'Explosivo',
        description: 'Los proyectiles explotan e inflingen un daño de arma del 20%',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '52',
        stars: 2,
        name: 'Feroz',
        description: 'Refuerza el aguante de las extremidades según la racha de bajas',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '53',
        stars: 2,
        name: 'Fuerza',
        description: '+2 Fuerza',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '54',
        stars: 2,
        name: 'Glotonería',
        description: 'El hambre y la sed aumentan un 10% mas despacio',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human'],
        unlocked: false,
    },
    {
        id: '55',
        stars: 2,
        name: 'Golpeador',
        description: '+50% daño por golpe',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '56',
        stars: 2,
        name: 'Ignífugo',
        description: '+50 resistencia al fuego',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '57',
        stars: 2,
        name: 'Incapacitante',
        description: '+50% daño a las extremidades',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '58',
        stars: 2,
        name: 'Inercia',
        description: 'Recuperas 15 puntos de acción con cada baja',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '59',
        stars: 2,
        name: 'Inteligencia',
        description: '+2 Inteligencia',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '60',
        stars: 2,
        name: 'Materiales peligrosos',
        description: '+50 resistencia a la radiación',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '61',
        stars: 2,
        name: 'Percepción',
        description: '+2 Percepción',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '62',
        stars: 2,
        name: 'Peso pesado',
        description: '+40% daño de ataque potente',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '142',
        stars: 2,
        name: 'Potenciado',
        description: '+5% regeneración de puntos de acción',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '63',
        stars: 2,
        name: 'Resistencia',
        description: '+2 Resistencia',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '64',
        stars: 2,
        name: 'Respuesta',
        description: '+50% reflejo del daño bloqueado',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '65',
        stars: 2,
        name: 'Robusto',
        description: 'Recibe un 7% menos de daño por explosión',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '66',
        stars: 2,
        name: 'Suerte',
        description: '+2 Suerte',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '67',
        stars: 2,
        name: 'Tibio',
        description: '+50 resistencia criogénica',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '68',
        stars: 2,
        name: 'VATS mejorado',
        description: '+50% probabilidad de golpear un objetivo en VATS',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '70',
        stars: 2,
        name: 'Veloz',
        description: '+25% velocidad del arma',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '69',
        stars: 2,
        name: 'Vital',
        description: '+50% daño crítico',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '71',
        stars: 2,
        name: 'Último disparo',
        description: 'La última bala de un cargador tiene una probabilidad del 25% de infringir un +100% de daño',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    // ⭐⭐⭐ 3 STARS
    {
        id: '79',
        stars: 3,
        name: 'Acrobático',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '80',
        stars: 3,
        name: 'Agente secreto',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '81',
        stars: 3,
        name: 'Agilidad',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '82',
        stars: 3,
        name: 'Alpinista',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '83',
        stars: 3,
        name: 'Bloqueador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '84',
        stars: 3,
        name: 'Brío',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '85',
        stars: 3,
        name: 'Buzo',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '86',
        stars: 3,
        name: 'Bárbaro',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '87',
        stars: 3,
        name: 'Caballero',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '88',
        stars: 3,
        name: 'Carisma',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '89',
        stars: 3,
        name: 'Centinela',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '90',
        stars: 3,
        name: 'Defensor',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '91',
        stars: 3,
        name: 'Descerrajador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '92',
        stars: 3,
        name: 'Disipación',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '93',
        stars: 3,
        name: 'Durabilidad',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '94',
        stars: 3,
        name: 'Electrificado',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '95',
        stars: 3,
        name: 'En llamas',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '96',
        stars: 3,
        name: 'Fantasmal',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '97',
        stars: 3,
        name: 'Firme',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '98',
        stars: 3,
        name: 'Fuerza',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '99',
        stars: 3,
        name: 'Golpe de suerte',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '100',
        stars: 3,
        name: 'Gélido',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '101',
        stars: 3,
        name: 'Infatigable',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '102',
        stars: 3,
        name: 'Inteligencia',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '103',
        stars: 3,
        name: 'Ligeros',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '104',
        stars: 3,
        name: 'Municionero',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '105',
        stars: 3,
        name: 'Percepción',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '106',
        stars: 3,
        name: 'Peso ligero',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '107',
        stars: 3,
        name: 'Portador de armas',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '108',
        stars: 3,
        name: 'Rata de carga',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '109',
        stars: 3,
        name: 'Reflejo',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },

    // ⭐⭐⭐⭐ 4 STARS
    {
        id: '110',
        stars: 4,
        name: 'Agresor',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '111',
        stars: 4,
        name: 'Amante de la adrenalina',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '112',
        stars: 4,
        name: 'Bravucón',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '113',
        stars: 4,
        name: 'Carga',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '114',
        stars: 4,
        name: 'Cargador al máximo',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '115',
        stars: 4,
        name: 'Chu, chu',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '116',
        stars: 4,
        name: 'Conductor',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '117',
        stars: 4,
        name: 'Corredor',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '118',
        stars: 4,
        name: 'Electricista',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '119',
        stars: 4,
        name: 'Escáner',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '120',
        stars: 4,
        name: 'Estabilizador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '121',
        stars: 4,
        name: 'Frío glacial',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '122',
        stars: 4,
        name: 'Incondicional',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '123',
        stars: 4,
        name: 'Inspiración radiactiva',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '124',
        stars: 4,
        name: 'Liberador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '125',
        stars: 4,
        name: 'Localizador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '126',
        stars: 4,
        name: 'Machacador',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '127',
        stars: 4,
        name: 'Matasanos',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '128',
        stars: 4,
        name: 'Matón',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '129',
        stars: 4,
        name: 'Miasma',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '130',
        stars: 4,
        name: 'Pirómano',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '131',
        stars: 4,
        name: 'Propulsión',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '132',
        stars: 4,
        name: 'Pulido',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '133',
        stars: 4,
        name: 'Pétreo',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '134',
        stars: 4,
        name: 'Ranger',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '135',
        stars: 4,
        name: 'Reflectante',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '136',
        stars: 4,
        name: 'Rejuvenecedor',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '137',
        stars: 4,
        name: 'Rompecombos',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '138',
        stars: 4,
        name: 'Rompehuesos',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '139',
        stars: 4,
        name: 'Rompelímites',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '140',
        stars: 4,
        name: 'Víbora',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
    {
        id: '141',
        stars: 4,
        name: 'Égida',
        description: '',
        category: ['ranged', 'melee', 'armor', 'power armor'],
        race: ['human', 'ghoul'],
        unlocked: false,
    },
];
